Added callback logic (to be tested)

diff --git a/board/shredos/fsoverlay/usr/bin/nwipe_launcher b/board/shredos/fsoverlay/usr/bin/nwipe_launcher
--- a/board/shredos/fsoverlay/usr/bin/nwipe_launcher
+++ b/board/shredos/fsoverlay/usr/bin/nwipe_launcher
@@ -757,6 +757,33 @@ do
 	fi
 		printf "______________________________________________________________________________\n" 2>&1  | tee -a transfer.log
 
+	# read the kernel command line for a callback URL to download and execute after
+	# the wipe and all transfers have completed.
+	# example: shredos_nwipe_callback="http://192.168.0.2/scripts/post_wipe.sh"
+	#
+	nwipe_callback_url=$(kernel_cmdline_extractor shredos_nwipe_callback)
+	if [ $? == 0 ]
+	then
+		printf "[`date "$date_format"`] Found shredos_nwipe_callback on kernel command line\n" 2>&1 | tee -a transfer.log
+		printf "[`date "$date_format"`] Downloading callback script from $nwipe_callback_url\n" 2>&1 | tee -a wget.log
+		wget --no-check-certificate -O /tmp/nwipe_callback.sh "$nwipe_callback_url" -nv >> wget.log 2>&1
+		if [ $? == 0 ]
+		then
+			printf "[`date "$date_format"`] Callback script downloaded successfully\n" 2>&1 | tee -a transfer.log
+			chmod +x /tmp/nwipe_callback.sh
+			printf "[`date "$date_format"`] Executing callback script\n" 2>&1 | tee -a transfer.log
+			/tmp/nwipe_callback.sh
+			if [ $? == 0 ]
+			then
+				printf "[`date "$date_format"`] Callback script completed successfully\n" 2>&1 | tee -a transfer.log
+			else
+				printf "[`date "$date_format"`] Callback script exited with an error\n" 2>&1 | tee -a transfer.log
+			fi
+		else
+			printf "[`date "$date_format"`] [FAILED] Could not download callback script from $nwipe_callback_url\n" 2>&1 | tee -a transfer.log
+		fi
+	fi
+
 	# If the user has specified `shredos_autoreboot=enable` on the kernel command line
 	#
 	if [ "$autoreboot" == "enable" ]
